### ISSUE TITLE
Other costs

### ISSUE THREAD

**Issue by Digital-Ark** [jrfernandes/ontario_energy_board#10]
Hi, I have recently figured out the Toronto Hydro billing formula to the dollar.

This currently scrapes:
``` 
<RRROffP>
<RRRMidP>
<RRROnP>
 ```

If we could also scrape:
``` 
<SC>
<LF>
<Net>
<Conn>
<WMSR>
<RRRP>
<SSS>
<GST>
<Rebate> 
```

I can write out or send you a spreadsheet that matches against your hydro bill to the dollar every month.

**Comment by Digital-Ark** [comment]
I exported my spreadsheet to Google Sheets so that anyone can view the billing formula.

Hoping this spurs some interest in pulling the rest of the XML data from the OEB site.  It contains *everything* needed to replicate your Toronto Hydro Bill (and very likely all other power utilities in Ontario).

https://docs.google.com/spreadsheets/d/14pV23ip7UQH6B72HYhsWEpsCbo_X1aII/edit?usp=sharing&ouid=105585911527314767707&rtpof=true&sd=true

**Comment by jrfernandes** [comment]
This is interesting. Thank you.

If I understand correctly, you're suggesting exposing the values of those other attributes via the added sensor so that you could leverage them to calculate your monthly bill. Is that correct?

**Comment by Digital-Ark** [comment]
Yes, together all the XML tags contained in the “Current Residential Rates” Open Data has all the information for residential customers on either the ToU or Tier rate plans to calculate their bill.

If you could pull the remaining attributes, Home Assistant users for all of the listed utilities could calculate their power costs for any period.

**Comment by jrfernandes** [comment]
These attributes are now live with the release [v0.3.2](https://github.com/jrfernandes/ontario_energy_board/releases/tag/v0.3.2)

**Comment by Digital-Ark** [comment]
This. Is. Amazing!

Thank you so much!  You even credited me and linked the spreadsheet, above and beyond.
