### ISSUE TITLE
Add a "Season" Attribute

### ISSUE THREAD

**Issue by maxistviews** [jrfernandes/ontario_energy_board#11]
OEB changes their rate based on the time of year, which I believe is already hard coded into this integration. I would find it useful if the season was surfaced in the attributes section for the sake of having one sensor for my automations. This is purely self-serving, but perhaps others would find this useful as an attribute.

![image](https://user-images.githubusercontent.com/17325179/197353026-06a73729-a18a-4ab0-9fe8-03e0479fc062.png)

**Comment by jrfernandes** [comment]
These attributes are now live with the release [v0.3.2](https://github.com/jrfernandes/ontario_energy_board/releases/tag/v0.3.2)
