### ISSUE TITLE
Waterloo North Hydro and Kitchener Wilmot Hydro have become Enova Power Corp

### ISSUE THREAD

**Issue by derekpurdy** [jrfernandes/ontario_energy_board#12]
Not sure if this is anything you have control over or if the data all comes from upstream, but Waterloo North Hydro and Kitchener Wilmot Hydro have become Enova Power Corp.

https://enovapower.com/kitchener-wilmot-hydro-inc-and-waterloo-north-hydro-inc-are-now-enova-power-corp/

**Comment by kwkid** [comment]
Thx for posting this. I noticed this morning that the Waterloo North Hydro Rate was showing unavailable in HA today.. A quick deletion of the existing integration and re-adding it back but choosing Enova_Power_Corp_Waterloo_North_Rate_Zone_Residential_Rate has resolved the issue for me
