### ISSUE TITLE
Consider adding OEB Natural Gas prices

### ISSUE THREAD

**Issue by ekkridon** [jrfernandes/ontario_energy_board#13]
Love this - it made using the energy dashboard much for useful. OEB also publishes gas prices and it would be handy to have cost values for those as well.

**Comment by N3rdP1um23** [comment]
A little late to respond, though this is something that I was working on and will submit a PR once it's ready! I'll try and set some time aside to continue working on it as I've had to put it off for a little bit.

It will be similar to the recent update https://github.com/jrfernandes/ontario_energy_board/releases/tag/v0.3.2, where it'll reveal all data points from the XML file provided by the OEB. It'll also be super useful as I was recently able to pull in gas meter usage into Home Assistant so having that data would be perfect!

**Comment by N3rdP1um23** [comment]
Just an update! I have the natural gas data pulling in and displaying alongside electricity sensors. With that, I just need a few more days to clean up and optimize some parts of the code before it's PR time!

I've also chatted with the team at OEB and was able to get a field-to-name mapper, as well as the calculations/formulas and would love to include that as well!

If you have electricity or natural gas sensors setup, it's going to be a great addition! Hopefully help estimate your next bill as well - which was my initial intent haha

**Comment by N3rdP1um23** [comment]
Just tagging the PR that represents/resolves this issue #22

**Comment by JAudi23** [comment]
Curious if there is an update for this? I just updated my gas rate manually in the Energy dashboard and wondered why the OEB integration didn't include gas rates, came here, and found this.  Thanks in advance!

**Comment by ryandkg** [comment]
+1
