### ISSUE TITLE
Integrate with Energy / Utility Meter

### ISSUE THREAD

**Issue by THX2112** [jrfernandes/ontario_energy_board#14]
I've been trying to integrate this with the Utility Meter and Energy functions in HA so that they can apply the proper TOU rate to objects that are being monitored for energy usage.

How can the rates from Ontario Energy Board be used as the TOU rates within HA so they can be used by Utility Meter and the Energy page?

I've gone through tonnes of posts about setting this up, but there's nothing specific for Ontario Energy Board and it's not working for me so there's something I'm not understanding or missing.

Has anyone set this up this way, and how did you do it?

**Comment by jrfernandes** [comment]
Were you able to install the component by following the instructions in the [README](https://github.com/jrfernandes/ontario_energy_board#readme)?

**Comment by THX2112** [comment]
It installs fine. There's nothing there that's relevant to my question.

I wanted to know how other people have it configured so the rates from Ontario Energy Board be used as the TOU rates within HA so they can be used by Utility Meter and the Energy page.

**Comment by jrfernandes** [comment]
Once you have the integration installed and added your energy company, you should be able to go to your Energy dashboard, and when adding consumption entities, you can use the option "Use an entity with current price" and select the newly added sensor.

![Image 2023-01-18 at 7 13 07 PM](https://user-images.githubusercontent.com/638906/213325650-37b26d5e-92bf-4c21-9b9a-a5322dbe2e4c.jpg)

**Comment by THX2112** [comment]
Thanks. That gave me the clues I needed to fix some of the issues. It's somewhat working now in the Energy dashboard, but still a lot of weirdness. I'll figure it out. Thanks again!
