### ISSUE TITLE
Tiered Pricing

### ISSUE THREAD

**Issue by theklunky** [jrfernandes/ontario_energy_board#15]
Would it be possible to add tiered pricing to this integration? In Winter months, the first 1000KWh are billed at 8.7cents/KWh and the rest at 10.3 cents/KWh. In summer the first 600KWh are billed at the lower rate. Hopefully other users could benefit from this. Cheers

**Comment by jrfernandes** [comment]
How would you suggest adding this? I'm thinking maybe adding two attributes for this, something like:
- `tier_1_amount` (e.g. 1000kWh)
- `tier_1_rate` (e.g. CA$0.087/kWh)
- `tier_2_rate` (e.g. CA$0.103/kWh)

Is this how you were thinking about it?

**Comment by theklunky** [comment]
There are two tier levels, one for winter and one for summer. I think summer is 750KWh for the first tier. I guess there would have to be a way to automatically switch from winter to summer and vice-versa. Would this be able to be integrated in the Energy portion of HA or would it only provide attribute to then make my own usage a pricing graphs?

**Comment by jrfernandes** [comment]
[This page here](https://www.oeb.ca/consumer-information-and-protection/electricity-rates) talks about the tiered pricing, which changes between summer and winter. The challenge here is that the XML file does not include the tier amount for summer and winter; it only includes one that matches the winter amount right now. I wonder if the XML will change once summer starts.

**Comment by theklunky** [comment]
At this point, I would be fine with inputting the tier threshold manually in the configuration when the switch happens between summer and winter and vice versa if that makes it easier for you.

**Comment by jrfernandes** [comment]
These attributes are now live with the release [v0.3.2](https://github.com/jrfernandes/ontario_energy_board/releases/tag/v0.3.2)
