### ISSUE TITLE
Ontario Energy Board Integration not loading in 2023.5.0b0

### ISSUE THREAD

**Issue by pgsylvestre** [jrfernandes/ontario_energy_board#23]
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/ontario_energy_board/__init__.py:21
Integration: Ontario Energy Board (documentation, issues)
First occurred: April 26, 2023 at 9:48:25 PM (3 occurrences)
Last logged: 12:01:41 AM

Error setting up entry Hydro Ottawa Limited (RESIDENTIAL) for ontario_energy_board
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ontario_energy_board/__init__.py", line 21, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by rtorchia** [comment]
getting the same error

**Comment by johnwalk61** [comment]
Same error here too. Right after the update

**Comment by kenlasko** [comment]
There was a ticket opened about this very thing back in February, where HA warned about the deprecation of async_setup_platforms. The integration owner never acknowledged or did anything about it. Hopefully the integration isn't abandoned already.  Maybe they're not getting notifications?

**Comment by johnwalk61** [comment]
I reverted to using a template for the tariff and a rest sensor to get rates pulling directly from OEB. Working well so far.
Looks like this integration might be abandoned.

**Comment by darknicht66** [comment]
@rtorchia I tested your PR on my system and it is working perfectly. Hopefully the project owner will merge soon.

**Comment by johnwalk61** [comment]
Thanks. Change worked perfectly.

**Comment by RoisinDubh79** [comment]
@rtorchia tested your fix on the container version of HA 2023.5.1 and it's working great.

**Comment by jrfernandes** [comment]
Thank you, @rtorchia, for the contribution. 

There's now a new release that includes the fix.
