### ISSUE TITLE
OEB breaks workday; holidays version conflicts

### ISSUE THREAD

**Issue by deftdawg** [jrfernandes/ontario_energy_board#29]
Per https://github.com/home-assistant/core/issues/93508

OEB depending on an old version of "holidays", this breaks the core workday sensor.

Not sure if there's an easy way sync this up going forward (can it be omitted or replaced with '>='?), but in the very least the version needs to come up to 0.21.13 to match core.

**Comment by jrfernandes** [comment]
This was fixed with release [v0.3.5](https://github.com/jrfernandes/ontario_energy_board/releases/tag/v0.3.5)

**Comment by jrfernandes** [comment]
This was fixed with release [v0.3.5](https://github.com/jrfernandes/ontario_energy_board/releases/tag/v0.3.5)
