### ISSUE TITLE
Peak rates missing last digit

### ISSUE THREAD

**Issue by maxistviews** [jrfernandes/ontario_energy_board#4]
Thank you for your work on this. 
I noticed that the prices on the attributes are missing last digit. off peak should be "0.08**2**", for instance. 

![image](https://user-images.githubusercontent.com/17325179/153715258-1b3c3a1c-cd39-46f8-8f1f-b091d8dc8939.png)

**Comment by jrfernandes** [comment]
That's just the UI rounding the number to 2 digits. The attribute does have the complete value:
![Image 2022-02-12 at 10 17 12 AM](https://user-images.githubusercontent.com/638906/153717082-705164bf-ac97-4b05-b42d-e02e035c983a.jpg)

**Comment by maxistviews** [comment]
Ah my bad! On the phone I couldn't see those. Thanks for checking.
