### ISSUE TITLE
ULO - Hydro Ottawa Limited (RESIDENTIAL) [Electricity] Rate sensor (under Ontario Energy Board v0.4.0) is not working anymore 

### ISSUE THREAD

**Issue by epanosian1** [jrfernandes/ontario_energy_board#44]
After today's OEB update, I proceeded to delete the old Integration entity, rebooted HA, added the new one, rebooted again:
After all the above steps now I get the following error message:
"This entity is no longer being provided by the ontario_energy_board integration. If the entity is no longer in use, delete it in settings."
<img width="582" alt="Screen Shot 2024-04-19 at 5 14 04 PM" src="https://github.com/jrfernandes/ontario_energy_board/assets/165337402/0de36248-5487-4a48-b61a-bee26bab4e4f">

I enabled debug logging, here are a few lines:
KeyError: 'ulo_on_peak'
2024-04-19 17:36:51.898 DEBUG (MainThread) [custom_components.ontario_energy_board.coordinator] Finished fetching ontario_energy_board data in 0.000 seconds (success: True)
2024-04-19 17:36:51.905 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.hydro_ottawa_limited_residential_electricity_rate fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in async_update_ha_state
    await self.async_device_update()

thank you,
EPA

**Comment by inco** [comment]
Have the same issue

**Comment by epanosian1** [comment]
more information:
It works without selecting 'Enable ULO rates'. I've tried deleting and re-adding several times without the ULO successfully, but with the ULO unsuccessfully.

**Comment by alexpalmer** [comment]
Same. Looks like something broke with this update.

**Comment by epanosian1** [comment]
yes, broken for sure.. 
yesterday started to work after I installed the old version [Hydro Ottawa Limited (RESIDENTIAL) Rate].
