### ISSUE TITLE
Sensor potentially not updating

### ISSUE THREAD

**Issue by maxistviews** [jrfernandes/ontario_energy_board#5]
Hey, Im not sure what I could be doing wrong here, but the sensor does not seem to be updating:

![image](https://user-images.githubusercontent.com/17325179/154707639-95d355a4-0b48-49a5-bc6c-490a2c7462e1.png)

In this image we should have already been on peak, but it hasnt changed. I have deleted and re-installed the component, that was the last change you see in the graph. Since then it hasnt updated.

Any ideas would be appreciated. Thanks for your hard work!

**Comment by Cogginshome** [comment]
I'm having the same issue

**Comment by jrfernandes** [comment]
dang it. the last version changed the coordinator interval to 24 hours to get the rates, since the current peak is not calculated in code instead of pulling from the web. That made the sensor to only update every 24 hours as well. I'll get a fix for this soon.

**Comment by jrfernandes** [comment]
This is now solved with release v0.3.0
