### ISSUE TITLE
Invalid currency code : CA$/kWh

### ISSUE THREAD

**Issue by McGeaverBeaver** [jrfernandes/ontario_energy_board#6]
Sensor is reporting incorrect currency code as per Home Assistant. 

RangeError: Invalid currency code : CA$/kWh

Code should be CAD/kWh

Thank you.

**Comment by jrfernandes** [comment]
I'm curious, where/how did you see that error?

**Comment by McGeaverBeaver** [comment]
This was in the home assistant logs from the UI. I would see it after
visiting a dashboard with the entity. It's no longer being displayed in the
logs, if I recreate I will post more details. Sorry I left them out the
first time.

**Comment by jrfernandes** [comment]
That's odd. What currency do y'all have set under Settings > System > General (/config/general)?

Is it `CAD`?

![Screen Shot 2022-05-13 at 5 19 23 PM](https://user-images.githubusercontent.com/638906/168391095-7f935526-8ca4-4065-a0ed-1ba78d8dfd17.png)

**Comment by kerhbal** [comment]
@jrfernandes yep
<img width="701" alt="Safari-Settings – Home Assistant--2022-05-13 at 17 25 16" src="https://user-images.githubusercontent.com/11629684/168391564-b88e1d40-5864-47c8-a6cc-0686aff42050.png">

**Comment by kerhbal** [comment]
though I found that the value works in energy dashboard with currency, just something is weird with that error message(I still can see it despite currency works)
<img width="962" alt="Safari-Energy – Home Assistant--2022-05-13 at 17 26 40" src="https://user-images.githubusercontent.com/11629684/168391839-7fa6221b-8e98-4377-a568-ccdd91274fb2.png">
