### ISSUE TITLE
How do I add this to dashboard?

### ISSUE THREAD

**Issue by mjb83** [jrfernandes/ontario_energy_board#8]
Sorry for incredible noob question, but I can't seem to find the entity for this once I've installed via HACS?

My assumption is that an entity is created when I install, but I'm not seeing anything related to Ontario energy when I scroll through my entities.

**Comment by kwkid** [comment]
It's a 2-step install...
1. Install via HACS. Seems like you have done this already.
2. Go to Settings -> Device and Services -> Add Integration...you should now see this
3. Install

![image](https://user-images.githubusercontent.com/77468155/169707169-b46a4a4c-d92f-4cc6-9db6-0f664beb7635.png)

**Comment by mjb83** [comment]
Yep, super noon couldn't find it.

Thanks very much for taking the time to answer. Working great!

**Comment by mjb83** [comment]
What about mapping the attributes so I can have each of them on their own entity card? Is this possible?

For instance, I have "sensor.alectra_utilities_corporation_brampton_rate_zone_residential_rate" currently set as a gauge card showing off_peak as 'green' zone, mid_peak as 'yellow' zone, and on_peak as 'red' zone. Is there a way for me to show the attribute 'active_peak' as its own entity so I can have it on its own entity card?

Been trying something like this is configuration.yaml but I can't seem to get it to map:

sensor:
  - platform: alectra_utilities

  - platform: template1
    sensors:
      alectra_utilities_active_peak:
        value_template: "{{states.sensor.alectra_utilities_corporation_brampton_rate_zone_residential_rate.attributes.active_peak}}"

**Comment by kwkid** [comment]
for your example try this.... be careful around spacing / indentation

- platform: template
  sensors:
     alectra_utilities_active_peak:
     value_template: "{{ state_attr('sensor.alectra_utilities_corporation_brampton_rate_zone_residential_rate','active_peak') }}"
     friendly_name: "Brampton Hydro Rate"

1st line: start with dash <space> platform: template (you had template1)
2nd line...align sensors under platform
3rd line...indent 2 spaces for sensor name
4th line...align value_template under alectra..... (double quotes with inner single quotes)
5th line...align friendly_name under alectra....

once your sensor is setup...you reference it as sensor.alectra_utilities_active peak in your Entities card.

drop the platform: alectra_utilities tag...

**Comment by kwkid** [comment]
should be like this...seems the editor in this tool drops the spaces...

![image](https://user-images.githubusercontent.com/77468155/169842898-df92a0e2-4ae3-4009-8a7d-e4125d58d37a.png)

**Comment by mjb83** [comment]
I feel like I need a line above - platform: template

Does the first line need to be the hacs install name? I tried sensor below but I'm getting an error for duplicate key.

#OntarioPowerAttributes
sensor:
  - platform: template
    sensors:
      alectra_utilities_active_peak:
      value_template: "{{ state_attr('sensor.alectra_utilities_corporation_brampton_rate_zone_residential_rate','active_peak') }}"
      friendly_name: "Brampton Hydro Rate"

**Comment by jrfernandes** [comment]
This should work:
```yaml
- platform: template
  sensors:
    alectra_utilities_active_peak:
      value_template: "{{ state_attr('sensor. alectra_utilities_corporation_brampton_rate_zone_residential_rate', 'active_peak') }}"
      friendly_name: Alectra Active Peak
```

Line 3 is the ID of your new sensor. Make sure it's unique.
Line 4 gets the active peak from the attribute of the OEB sensor. Make sure the sensor ID matches what you have.
Line 5 is just the friendly name for the sensor, it can be anything.

**Comment by kwkid** [comment]
It depends on whether this is the only sensor you have and where is the sensor stored (are your sensors in configuration.yaml or have you broken the sensors out into a separate file sensor.yaml)…
Personally I have broken out my sensors into a separate sensor.yaml file with a reference to this file in configuration.yaml..there are plenty of examples like this..

On May 23, 2022, at 11:40 AM, mjb83 ***@***.***> wrote:

﻿

I feel like I need a line above - platform: template

Does the first line need to be the hacs install name? I tried sensor below but I'm getting an error for duplicate key.

#OntarioPowerAttributes
sensor:

  *   platform: template
sensors:
alectra_utilities_active_peak:
value_template: "{{ state_attr('sensor.alectra_utilities_corporation_brampton_rate_zone_residential_rate','active_peak') }}"
friendly_name: "Brampton Hydro Rate"
